//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessController.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmar Senha.
        /// </summary>
        internal static string lbl_confirmar {
            get {
                return ResourceManager.GetString("lbl_confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        internal static string lbl_senha {
            get {
                return ResourceManager.GetString("lbl_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário.
        /// </summary>
        internal static string lbl_usuario {
            get {
                return ResourceManager.GetString("lbl_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha atualizada com sucesso!.
        /// </summary>
        internal static string msg_alt_senha {
            get {
                return ResourceManager.GetString("msg_alt_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O seguinte erro ocorreu: .
        /// </summary>
        internal static string msg_error {
            get {
                return ResourceManager.GetString("msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Necessário alterar a senha no primeiro login.
        /// </summary>
        internal static string msg_first_login {
            get {
                return ResourceManager.GetString("msg_first_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A primeira senha não é igual a segunda.
        /// </summary>
        internal static string msg_senha_diferente {
            get {
                return ResourceManager.GetString("msg_senha_diferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha precisa conter no mínimo 1 caracter especial.
        /// </summary>
        internal static string msg_senha_especial {
            get {
                return ResourceManager.GetString("msg_senha_especial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha precisa conter no mínimo 1 caracter maiúsculo.
        /// </summary>
        internal static string msg_senha_maiusculo {
            get {
                return ResourceManager.GetString("msg_senha_maiusculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha precisa conter no mínimo 8 caracter e no máximo 18.
        /// </summary>
        internal static string msg_senha_minMax {
            get {
                return ResourceManager.GetString("msg_senha_minMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha precisa conter no mínimo 1 caracter minúsculo.
        /// </summary>
        internal static string msg_senha_minusculo {
            get {
                return ResourceManager.GetString("msg_senha_minusculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha precisa conter no mínimo 1 número.
        /// </summary>
        internal static string msg_senha_numero {
            get {
                return ResourceManager.GetString("msg_senha_numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        internal static string msg_us_not_found {
            get {
                return ResourceManager.GetString("msg_us_not_found", resourceCulture);
            }
        }
    }
}
