//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessController.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTPESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MTPESSOA()
        {
            this.MTUSUARIO = new HashSet<MTUSUARIO>();
        }
    
        public int MTPESSOA_ID { get; set; }
        public string MTPESSOA_NOME { get; set; }
        public string MTPESSOA_SOBRENOME { get; set; }
        public System.DateTime MTPESSOA_NASCIMENTO { get; set; }
        public string MTPESSOA_MAE { get; set; }
        public string MTPESSOA_CPF { get; set; }
        public string MTPESSOA_RG { get; set; }
        public string MTPESSOA_CEL { get; set; }
        public string MTPESSOA_TEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTUSUARIO> MTUSUARIO { get; set; }
    }
}
